"""ingestion metadata phase5

Revision ID: 99749098d60e
Revises: d21ef5ef5733
Create Date: 2026-07-16 18:24:23.005279
"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision = '99749098d60e'
down_revision = 'd21ef5ef5733'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_index(op.f('ix_cmetadata_gin'), table_name='langchain_pg_embedding', postgresql_ops={'cmetadata': 'jsonb_path_ops'}, postgresql_using='gin')
    op.execute("DROP INDEX IF EXISTS ix_cmetadata_gin")
    # op.drop_table('langchain_pg_embedding')
    # op.drop_table('langchain_pg_collection')
    op.execute("DROP TABLE IF EXISTS langchain_pg_embedding CASCADE")
    op.execute("DROP TABLE IF EXISTS langchain_pg_collection CASCADE")
    op.add_column('tenant_ingest_metadata', sa.Column('status', sa.Enum('PENDING', 'PROCESSING', 'COMPLETED', 'FAILED', name='ingestionstatus', native_enum=False), server_default='PENDING', nullable=False))
    op.add_column('tenant_ingest_metadata', sa.Column('error', sa.Unicode(length=2000), nullable=True))
    op.add_column('tenant_ingest_metadata', sa.Column('chunk_count', sa.Integer(), nullable=True))
    op.add_column('tenant_ingest_metadata', sa.Column('security_level', sa.Enum('PUBLIC', 'PRIVATE', 'SECRET', name='securitylevel', native_enum=False), server_default='PUBLIC', nullable=False))
    op.add_column('tenant_ingest_metadata', sa.Column('department_id', sa.Unicode(length=50), nullable=True))
    op.add_column('tenant_ingest_metadata', sa.Column('brand_id', sa.Unicode(length=50), nullable=True))


# def upgrade() -> None:
#     # ### commands auto generated by Alembic - please adjust! ###
#     op.drop_index(op.f('ix_cmetadata_gin'), table_name='langchain_pg_embedding', postgresql_ops={'cmetadata': 'jsonb_path_ops'}, postgresql_using='gin', if_exists=True)
#     op.drop_table('langchain_pg_embedding')
#     op.drop_table('langchain_pg_collection')
#     op.add_column('tenant_ingest_metadata', sa.Column('status', sa.Enum('PENDING', 'PROCESSING', 'COMPLETED', 'FAILED', name='ingestionstatus', native_enum=False), server_default='PENDING', nullable=False))
#     op.add_column('tenant_ingest_metadata', sa.Column('error', sa.Unicode(length=2000), nullable=True))
#     op.add_column('tenant_ingest_metadata', sa.Column('chunk_count', sa.Integer(), nullable=True))
#     op.add_column('tenant_ingest_metadata', sa.Column('security_level', sa.Enum('PUBLIC', 'PRIVATE', 'SECRET', name='securitylevel', native_enum=False), server_default='PUBLIC', nullable=False))
#     op.add_column('tenant_ingest_metadata', sa.Column('department_id', sa.Unicode(length=50), nullable=True))
#     op.add_column('tenant_ingest_metadata', sa.Column('brand_id', sa.Unicode(length=50), nullable=True))
#     # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tenant_ingest_metadata', 'brand_id')
    op.drop_column('tenant_ingest_metadata', 'department_id')
    op.drop_column('tenant_ingest_metadata', 'security_level')
    op.drop_column('tenant_ingest_metadata', 'chunk_count')
    op.drop_column('tenant_ingest_metadata', 'error')
    op.drop_column('tenant_ingest_metadata', 'status')
    op.create_table('langchain_pg_collection',
    sa.Column('uuid', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('cmetadata', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('uuid', name=op.f('langchain_pg_collection_pkey')),
    sa.UniqueConstraint('name', name=op.f('langchain_pg_collection_name_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_table('langchain_pg_embedding',
    sa.Column('id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('collection_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('embedding', sa.NullType(), autoincrement=False, nullable=True),
    sa.Column('document', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('cmetadata', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['collection_id'], ['langchain_pg_collection.uuid'], name=op.f('langchain_pg_embedding_collection_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('langchain_pg_embedding_pkey'))
    )
    op.create_index(op.f('ix_cmetadata_gin'), 'langchain_pg_embedding', ['cmetadata'], unique=False, postgresql_ops={'cmetadata': 'jsonb_path_ops'}, postgresql_using='gin')
    # ### end Alembic commands ###