"""baseline schema v2

Revision ID: d21ef5ef5733
Revises: 
Create Date: 2026-07-15 12:39:19.706150
"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision = 'd21ef5ef5733'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('brands',
    sa.Column('name', sa.Unicode(length=255), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('chat',
    sa.Column('external_chat_id', sa.Unicode(length=22), nullable=False),
    sa.Column('external_user_id', sa.Unicode(length=255), nullable=True),
    sa.Column('title', sa.Unicode(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('model', sa.Unicode(length=255), nullable=False),
    sa.Column('channel_type', sa.Enum('Web', 'Mobile', 'Whatsapp', 'Alexa', name='channel', native_enum=False), nullable=True),
    sa.Column('first_name', sa.Unicode(length=255), nullable=True),
    sa.Column('last_name', sa.Unicode(length=255), nullable=True),
    sa.Column('user_consent', sa.Boolean(), nullable=True),
    sa.Column('email', sa.Unicode(length=255), nullable=True),
    sa.Column('brand_id', sa.Unicode(length=255), nullable=False),
    sa.Column('category', sa.Enum('GENERAL', 'ISSUES', name='categoryenum', native_enum=False), nullable=False),
    sa.Column('sub_category', sa.Enum('PACKAGING', 'PRODUCT_INFORMATION', 'QUALITY', 'SMELL_OR_ODOR', 'WEIGHT', 'FOREIGN_MATTER', 'INSECTS', 'MICROORGANISM', 'ALLERGIES_OTHER', 'COMPLIMENTS_OTHER', 'COUPONS_OTHER', 'DAMAGE_OTHER', 'DIRECTIONS_MISPRINT_OTHER', 'DISPLEASED_OTHER', 'RECIPES_OTHER', 'OTHER_DEPARTMENT_OTHER', 'ILLNESS_OTHER', 'LEGAL_OTHER', name='subcategoryenum', native_enum=False), nullable=True),
    sa.Column('issue_description', sa.Unicode(length=5000), nullable=True),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('external_chat_id')
    )
    op.create_table('tenant',
    sa.Column('name', sa.Unicode(length=255), nullable=False),
    sa.Column('external_uid', sa.Unicode(length=22), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('external_uid'),
    sa.UniqueConstraint('name')
    )
    op.create_table('department',
    sa.Column('name', sa.Unicode(length=255), nullable=False),
    sa.Column('tenant_id', sa.BigInteger(), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('designation',
    sa.Column('name', sa.Unicode(length=255), nullable=False),
    sa.Column('tenant_id', sa.BigInteger(), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('division',
    sa.Column('name', sa.Unicode(length=255), nullable=False),
    sa.Column('tenant_id', sa.BigInteger(), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('role',
    sa.Column('name', sa.Unicode(length=255), nullable=False),
    sa.Column('description', sa.Unicode(length=255), nullable=True),
    sa.Column('external_uid', sa.Unicode(length=22), nullable=False),
    sa.Column('tenant_id', sa.BigInteger(), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('external_uid'),
    sa.UniqueConstraint('name', 'tenant_id', name='_role_tenant_uc')
    )
    op.create_table('tenant_ingest_metadata',
    sa.Column('external_uid', sa.Unicode(length=22), nullable=False),
    sa.Column('source_type', sa.Unicode(length=50), nullable=True),
    sa.Column('source_path', sa.Unicode(length=1024), nullable=True),
    sa.Column('tenant_id', sa.BigInteger(), nullable=True),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('external_uid')
    )
    op.create_table('users',
    sa.Column('email', sa.Unicode(length=255), nullable=False),
    sa.Column('password', sa.Unicode(length=255), nullable=False),
    sa.Column('first_name', sa.Unicode(length=255), nullable=False),
    sa.Column('last_name', sa.Unicode(length=255), nullable=True),
    sa.Column('dob', sa.Unicode(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('external_user_id', sa.Unicode(length=255), nullable=False),
    sa.Column('security_clearance', sa.Enum('PUBLIC', 'PRIVATE', 'SECRET', name='securitylevel', native_enum=False), server_default='PUBLIC', nullable=False),
    sa.Column('is_developer', sa.Boolean(), nullable=False),
    sa.Column('user_picture', sa.Unicode(length=255), nullable=True),
    sa.Column('external_uid', sa.Unicode(length=22), nullable=False),
    sa.Column('department_id', sa.BigInteger(), nullable=False),
    sa.Column('designation_id', sa.BigInteger(), nullable=False),
    sa.Column('division_id', sa.BigInteger(), nullable=False),
    sa.Column('tenant_id', sa.BigInteger(), nullable=False),
    sa.Column('role_id', sa.BigInteger(), nullable=False),
    sa.Column('brand_id', sa.BigInteger(), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['brand_id'], ['brands.id'], ),
    sa.ForeignKeyConstraint(['department_id'], ['department.id'], ),
    sa.ForeignKeyConstraint(['designation_id'], ['designation.id'], ),
    sa.ForeignKeyConstraint(['division_id'], ['division.id'], ),
    sa.ForeignKeyConstraint(['role_id'], ['role.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('external_uid'),
    sa.UniqueConstraint('external_user_id')
    )
    op.create_table('user_sessions',
    sa.Column('session_id', sa.Unicode(length=22), nullable=False),
    sa.Column('external_user_id', sa.Unicode(length=255), nullable=False),
    sa.Column('start_datetime', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('end_datetime', sa.DateTime(), nullable=True),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['external_user_id'], ['users.external_user_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('session_id')
    )
    op.create_table('chat_sessions',
    sa.Column('external_chat_id', sa.Unicode(length=22), nullable=False),
    sa.Column('session_id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['external_chat_id'], ['chat.external_chat_id'], ),
    sa.ForeignKeyConstraint(['session_id'], ['user_sessions.id'], ),
    sa.PrimaryKeyConstraint('external_chat_id', 'session_id')
    )
    op.create_table('conversations',
    sa.Column('external_chat_id', sa.Unicode(length=22), nullable=False),
    sa.Column('question', sa.TEXT(), nullable=True),
    sa.Column('answer', sa.TEXT(), nullable=True),
    sa.Column('reaction', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('external_conv_id', sa.Unicode(length=22), nullable=False),
    sa.Column('is_regenerate', sa.Boolean(), nullable=False),
    sa.Column('session_id', sa.BigInteger(), nullable=False),
    sa.Column('response_time', sa.Float(), nullable=True),
    sa.Column('answer_relevance', sa.Float(), nullable=True),
    sa.Column('context_relevance', sa.Float(), nullable=True),
    sa.Column('groundedness', sa.Float(), nullable=True),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['external_chat_id'], ['chat.external_chat_id'], ),
    sa.ForeignKeyConstraint(['session_id'], ['user_sessions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('external_conv_id')
    )
    op.create_table('conversation_sources',
    sa.Column('conversation_id', sa.BigInteger(), nullable=False),
    sa.Column('source_uid', sa.BigInteger(), nullable=True),
    sa.Column('distance', sa.Float(), nullable=False),
    sa.Column('doc_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ),
    sa.ForeignKeyConstraint(['source_uid'], ['tenant_ingest_metadata.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('conversation_id', 'source_uid', name='unique_conv_source')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('conversation_sources')
    op.drop_table('conversations')
    op.drop_table('chat_sessions')
    op.drop_table('user_sessions')
    op.drop_table('users')
    op.drop_table('tenant_ingest_metadata')
    op.drop_table('role')
    op.drop_table('division')
    op.drop_table('designation')
    op.drop_table('department')
    op.drop_table('tenant')
    op.drop_table('chat')
    op.drop_table('brands')
    # ### end Alembic commands ###